### ISSUE TITLE
Go To Source In IDE not working

### ISSUE THREAD

**Issue by kqtran1** [findtheflow/Feedback#21]
Clicking on "Go To Source In IDE" doesn't do anything.

- Flow version v20170718200811
- MacOs Sierra
- Intellij Ultimate 2017.2

I have the same behavior with multiple browsers: Chrome, Safari, Firefox

**Comment by YoannBuch** [comment]
Thanks for reporting this issue.

There is a know bug where "Go To Source In IDE" only works when the source belongs to the latest project you opened in IntelliJ.

For example : if you open project A, record something with Flow, open project B, click on "Go To Source In IDE", Flow will try to find the corresponding source in project B instead of A.

Is this your case?

**Comment by kqtran1** [comment]
Hi,

I've tested it again by just opening a single Intellij project and by running a Flow analysis, i still have the same issue.

I did the same test on another MacOs (same config), i have the same issue.

Any way i can help with this issue?

**Comment by YoannBuch** [comment]
After you tried the "Go To Source In IDE" functionality one more time, can you send the logs to contact@findtheflow.io? They are located in ${User Directory}/.flow/logs. Thanks.

**Comment by kqtran1** [comment]
Strangely "Go To Source In IDE" is working now, and i have no idea why.
The next time it doesn't work, i'll send you the logs.

Thanks

**Comment by YoannBuch** [comment]
Sounds good, thanks!
